### ISSUE TITLE
Setup failed, after updating homeassistant to 2023.3.6

### ISSUE THREAD

**Issue by Elanoran** [RasmusGodske/homeassistant-nrgiprices#1]
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 16.25.05 (1 occurrences)
Last logged: 16.25.05
Setup failed for custom integration nrgi_prices: Requirements for nrgi_prices not found: ['requests==2.28.1'].

Removing the following line in manifest.json - "requirements": , was a temp fix for me:
`"requests==2.28.1",`

**Comment by Elanoran** [comment]
After some further reading, the changelog from: Release 2023.3.1 - March 2
https://github.com/home-assistant/core/pull/88956
Bump requests to 2.28.2

Changed the version: 
`"requests==2.28.2",`

Should fix it

**Comment by RasmusGodske** [comment]
Thanks for the taking your time, bringing up this issue.
I have updated the library version, and bumped the version of the integration.
